# -*- coding: utf-8 -*-
"""MPaGE configuration.

MPaGE only configures the meta-level heuristic evolution.  API keys, the model
name, temperature and retry policy already live in ``data/config.py`` and are
consumed through ``llm.client.LLMClient``, so they are intentionally *not*
repeated here (see section 5 of the project guide).
"""

MPAGE_CONFIG = {
    # Meta-level heuristic population
    "heuristic_population_size": 6,

    # Number of meta-level evolution generations
    "meta_generations": 10,

    # Number of solution-level NSGA-II generations used to evaluate
    # one heuristic.
    "inner_generations": 10,

    # Inner NSGA-II population
    "inner_population_size": 40,

    # Number of initial heuristics generated by LLM
    "initial_llm_heuristics": 6,

    # Number of heuristics selected from Pareto/grid population
    "elite_heuristics": 4,

    # LLM calls
    "enable_llm": True,

    # One LLM call may generate several heuristics.
    "generation_batch_size": 3,

    # Semantic clustering
    "semantic_clusters": 3,

    # Pareto grid resolution
    "grid_bins": 5,

    # Cross-cluster crossover probability
    "crossover_probability": 0.7,

    # Same-cluster mutation probability
    "mutation_probability": 0.8,

    # Maximum number of LLM-generated heuristic operations
    "max_heuristic_steps": 5,

    # Random seed
    "seed": 42,

    # Keep complete inner search history
    "save_inner_history": True,

    # Ratio of heuristic-generated seed chromosomes inside the initial
    # NSGA-II population (section 25 of the guide: 30% heuristic / 70% random).
    "heuristic_seed_ratio": 0.3,
}